### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by skorpios1027** [irbyk/Plex-Discord-Bot_V2#11]
When issuing the npm install command the install errors out in the ffmpg-static module.  The relevant output is as follows:

/home/nodeproxy/Plex-Discord-Bot_V2/node_modules/ffmpeg-static/install.js:52
  url = new URL(url)
  ^

ReferenceError: URL is not defined
    at normalizeS3Url (/home/nodeproxy/Plex-Discord-Bot_V2/node_modules/ffmpeg-static/install.js:52:3)
    at Object.<anonymous> (/home/Plex-Discord-Bot_V2/node_modules/ffmpeg-static/install.js:61:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Any ideas on how to fix this?

**Comment by eneswritescode** [comment]
you never actually installed ffmpeg. Using the ffmpeg node module won't get you anywhere unless you install the binaries.

https://www.ffmpeg.org/download.html

**Comment by skorpios1027** [comment]
Great, thanks I'll give that a go.

**Comment by skorpios1027** [comment]
Got it working - the ffmpeg was the issue.

**Comment by irbyk** [comment]
Actually, the [ffmpeg-static module](https://www.npmjs.com/package/ffmpeg-static) install the ffmpeg binaries and the JS wrapper. So it's strange that the install had an issue.
