### ISSUE TITLE
Token invalid when its not

### ISSUE THREAD

**Issue by brendenspencer** [irbyk/Plex-Discord-Bot_V2#34]
(node:7931) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/opt/Plex/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/opt/Plex/index.js:13:8)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
(node:7931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by irbyk** [comment]
Do you use the docker image ?
Else, which Node version do you use ?

**Comment by brendenspencer** [comment]
v12.22.9

**Comment by brendenspencer** [comment]
> v12.22.9
12.22.9-dfsg-1ubuntu3

**Comment by irbyk** [comment]
On windows or linux directly ?

**Comment by brendenspencer** [comment]
Linux

**Comment by irbyk** [comment]
Dumb question : Are you sure you past the right Token ?

**Comment by irbyk** [comment]
I just did a fresh install and config and the bot work just fine for me.

**Comment by brendenspencer** [comment]
the one discord gave me

**Comment by irbyk** [comment]
Are you on the Discord server ?

**Comment by brendenspencer** [comment]
yes

**Comment by irbyk** [comment]
Can you write something on the "help" text channel there ?

**Comment by brendenspencer** [comment]
its my discord server?

**Comment by irbyk** [comment]
This one : https://discord.gg/c39aRhB
