### ISSUE TITLE
!mood not working

### ISSUE THREAD

**Issue by LiinaHime** [irbyk/Plex-Discord-Bot_V2#8]
hi,  its a great bot and everything works so far.
But I get an error in the console when i want to use the mood command and the bot never replies on that.

```
 ReferenceError: musics is not defined
    at Bot.playOneMood (C:\Users\<user>\Desktop\Plex-Discord-Bot_V2-master\app\bot.js:167:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.process (C:\Users\<user>\Desktop\Plex-Discord-Bot_V2-master\commands\mood.js:10:11)
ReferenceError: musics is not defined
    at Bot.playOneMood (C:\Users\<user>\Desktop\Plex-Discord-Bot_V2-master\app\bot.js:167:10)
    at Object.process (C:\Users\<user>\Desktop\Plex-Discord-Bot_V2-master\commands\mood.js:10:21)
    at Client.<anonymous> (C:\Users\<user>\Desktop\Plex-Discord-Bot_V2-master\app\music.js:63:21)
```

**Comment by irbyk** [comment]
It was an issue with the last modification (a keyword was missing in the code). Everything should work now ! 47c1c703a2c284e4f929ed77285aa477ebd7b212 fix it.
